# =============================================================================
# pipeline.conf
#
# Invocation configuration for SPARC pipeline.
#
# =============================================================================

# Required arguments
# Input/output directories, relative to conf file location or absolute
input=""
output=""

# Optional arguments
file_prefix=false
batch=false # Batch processing

# Pipeline configuration file, relative to conf file location or absolute;
# set to false to omit
cfg=false

# Models directories and configuration files, relative to conf file location
# or absolute; set to false to omit
models_chest_seg=false
models_chest_seg_cfg=false
models_heart_seg=false
models_heart_seg_cfg=false
models_reo=false
models_reo_cfg=false

# Behaviour
mode="semi_auto"
gui_mode="docker"
manual_stack_review=false
verbose=false
profile=false
log=false
debug=false
