# =============================================================================
# test.conf
#
# Invocation configuration for SPARC test.
#
# =============================================================================

# Required arguments
# Input/output directories, relative to conf file location or absolute
input=""
output=""
task="" # "segmentation" or "reorientation"
cfg=""
models=""

# Optional arguments
# Behaviour
save_qc=False # Save quality control metrics
save_indiv=False # Save individual models outputs
workers=8
verbose=False
log=True
