# =============================================================================
# train.conf
#
# Invocation configuration for SPARC train.
#
# =============================================================================

# Required arguments
# Input/output directories, relative to conf file location or absolute
input=("") # List for multi-domain training
output=""
task=""
cfg=""

# Optional arguments
# Models directories relative to conf file location or absolute; 
# set to false to omit
models=false

# Behaviour
folds=5
workers=8
verbose=False
log=True
